# Schema for configuration files of the Media entity Twitter: Automatic Pull module.

media.type.*.third_party.media_entity_twitter_pull:
  type: mapping
  label: 'Automatic Pull settings'
  mapping:
    usernames:
      type: sequence
      sequence:
        type: string
    count:
      type: integer
